# skhd — hotkey daemon for yabai (koekeishiya/skhd 0.3.9).
#
# Keybindings mirror the user's previous OmniWM layout (Option-based).
# skhd reads ~/.config/skhd/skhdrc at startup AND hot-reloads on change
# (SIGUSR1), so no rebuild is needed to tweak bindings.
#
# Requirements:
#   - Grant Accessibility permission to skhd (System Settings → Privacy &
#     Security → Accessibility). It needs the same as yabai.
{
  config,
  lib,
  pkgs,
  ...
}: let
  shared = import ../lib.nix {};

  # NOTE: skhdrc is generated by nix for reproducibility, but hot-reload
  # means the user can edit ~/.config/skhd/skhdrc directly afterwards.
  # A rebuild would overwrite manual edits.
  skhdrc = pkgs.writeText "skhdrc" ''
    # ── skhd hotkeys for yabai (managed by nix-darwin) ─────────────
    # NOTE: this is NOT a shell script — skhd parses it line by line.
    # PATH is inherited from the skhd-start wrapper (launchd PATH is minimal).

    # ── Workspaces (spaces) ──
    alt - 1 : yabai -m space --focus 1
    alt - 2 : yabai -m space --focus 2
    alt - 3 : yabai -m space --focus 3
    alt - 4 : yabai -m space --focus 4
    alt - 5 : yabai -m space --focus 5
    alt - 6 : yabai -m space --focus 6
    alt - 7 : yabai -m space --focus 7
    alt - 8 : yabai -m space --focus 8
    alt - 9 : yabai -m space --focus 9

    # Move window to workspace
    alt + shift - 1 : yabai -m window --space 1; yabai -m space --focus 1
    alt + shift - 2 : yabai -m window --space 2; yabai -m space --focus 2
    alt + shift - 3 : yabai -m window --space 3; yabai -m space --focus 3
    alt + shift - 4 : yabai -m window --space 4; yabai -m space --focus 4
    alt + shift - 5 : yabai -m window --space 5; yabai -m space --focus 5
    alt + shift - 6 : yabai -m window --space 6; yabai -m space --focus 6
    alt + shift - 7 : yabai -m window --space 7; yabai -m space --focus 7
    alt + shift - 8 : yabai -m window --space 8; yabai -m space --focus 8
    alt + shift - 9 : yabai -m window --space 9; yabai -m space --focus 9

    # ── Focus ──
    alt - left  : yabai -m window --focus west
    alt - down  : yabai -m window --focus south
    alt - up    : yabai -m window --focus north
    alt - right : yabai -m window --focus east
    alt - h     : yabai -m window --focus west
    alt - j     : yabai -m window --focus south
    alt - k     : yabai -m window --focus north
    alt - l     : yabai -m window --focus east
    alt - tab   : yabai -m window --focus recent

    # ── Move window (warp within space) ──
    alt + shift - left  : yabai -m window --warp west
    alt + shift - down  : yabai -m window --warp south
    alt + shift - up    : yabai -m window --warp north
    alt + shift - right : yabai -m window --warp east

    # Move window to prev/next space
    ctrl + alt + shift - up   : yabai -m window --space prev; yabai -m space --focus prev
    ctrl + alt + shift - down : yabai -m window --space next; yabai -m space --focus next

    # ── Resize / balance ──
    alt - equal : yabai -m space --balance
    alt - minus : yabai -m space --balance

    # ── Fullscreen ──
    alt - return : yabai -m window --toggle zoom-fullscreen

    # ── Tiling / stacking ──
    alt - t : yabai -m window --toggle split
    alt - v : yabai -m window --toggle zoom-parent

    # ── Float / native ──
    alt - f : yabai -m window --toggle float

    # ── Rotate / mirror ──
    alt - r : yabai -m space --rotate 90
    alt + shift - r : yabai -m space --mirror x-axis

    # ── Terminals ──
    alt - grave : open -a Ghostty

    # ── Misc ──
    alt + shift - q : yabai -m space --destroy
  '';

  # skhd needs PATH for the `yabai` calls in skhdrc (launchd PATH minimal)
  skhdStart = pkgs.writeShellScript "skhd-start" ''
    export PATH="/run/current-system/sw/bin:$PATH"
    exec ${pkgs.skhd}/bin/skhd
  '';
in {
  environment.systemPackages = [pkgs.skhd];

  system.activationScripts.extraActivation.text = lib.mkAfter ''
    install -d -m 0755 -o ${shared.username} -g staff ${shared.home}/.config/skhd
    rm -f ${shared.home}/.config/skhd/skhdrc
    install -m 0755 -o ${shared.username} -g staff ${skhdrc} ${shared.home}/.config/skhd/skhdrc
  '';

  launchd.user.agents.skhd = {
    serviceConfig = {
      ProgramArguments = ["${skhdStart}"];
      RunAtLoad = true;
      KeepAlive = true;
      ProcessType = "Interactive";
      StandardOutPath = "/tmp/skhd.log";
      StandardErrorPath = "/tmp/skhd.log";
    };
  };
}
