{
  lib,
  pkgs,
  ...
}:
let
  shared = import ../lib.nix { };

  # ── 生成的 env.nu ───────────────────────────────────────────────────
  # nushell 作为登录 shell 时不读 /etc/zshenv、不执行 path_helper,
  # 启动时 $env.PATH 为 nothing → 所有 nix/brew 工具(fastfetch、herdr…)
  # 都找不到。此文件在每次 nushell 启动时自动加载(默认 ~/.config/nushell/
  # env.nu),重建 PATH 与关键环境变量,顺序与 zsh 的 pathInit 严格一致。
  #
  # 只管理 env.nu;config.nu(prompt/alias/插件)留给用户自行维护。
  envNu = pkgs.writeText "env.nu" ''
    # GENERATED by nix-darwin (modules/shell/nushell.nix) — DO NOT EDIT.
    # 与 zsh lib.pathInit / environment.variables 同源;修改请改 nix 配置后 rebuild。

    # ── PATH(顺序与 zsh lib.pathInit 严格一致)────────────────────────
    ${shared.pathInitNu}

    # ── 代理(与 env.nix / nix.envVars 同一来源)───────────────────────
    $env.http_proxy = "${shared.proxyEnv.http_proxy}"
    $env.https_proxy = "${shared.proxyEnv.https_proxy}"
    $env.HTTP_PROXY = "${shared.proxyEnv.HTTP_PROXY}"
    $env.HTTPS_PROXY = "${shared.proxyEnv.HTTPS_PROXY}"
    $env.no_proxy = "${shared.proxyEnv.no_proxy}"
    $env.NO_PROXY = "${shared.proxyEnv.NO_PROXY}"
    $env.LARK_CLI_NO_PROXY = "${shared.shellProxyExtra.LARK_CLI_NO_PROXY}"

    # ── 编辑器 / 分页器 ───────────────────────────────────────────────
    $env.EDITOR = "nvim"
    $env.VISUAL = "nvim"
    $env.GIT_EDITOR = "nvim"
  '';
in
{
  # ── ~/.config/nushell/env.nu ────────────────────────────────────────
  # nix-darwin activation runs as root. There is no user-activation
  # surface any more (removed in nix-darwin ≥ 2024), so create the XDG
  # config path as root and chown to the primary user (same pattern as
  # programs/fetch.nix).
  system.activationScripts.nushell-env = {
    text = ''
      install -d -m 0755 -o ${shared.username} -g staff ${shared.home}/.config
      install -d -m 0755 -o ${shared.username} -g staff ${shared.home}/.config/nushell
      # `install` follows symlinks (would try to write into the read-only
      # nix-store target). Remove any existing file or symlink first.
      rm -f ${shared.home}/.config/nushell/env.nu
      install -m 0644 -o ${shared.username} -g staff ${envNu} ${shared.home}/.config/nushell/env.nu
    '';
  };
}
