{
  config,
  lib,
  pkgs,
  ...
}:
let
  shared = import ../lib.nix { };

  # ── 从单一来源生成环境变量赋值 ──────────────────────────────────────
  # environment.variables 被 nix-darwin 渲染进 set-environment, 由 /etc/zshenv
  # source 给所有 zsh —— 注意它**不**进 launchd (GUI app 的代理环境由
  # modules/shell/env.nix 的 launchd.user.agents.proxy-env 每次登录 setenv)。
  # 此处复用它生成 nu 语法,保证 zsh 与 nushell 永不漂移:
  # 任何变量改动(代理、LANG、PAGER…)rebuild 后两边自动同步。
  #
  # 处理:
  #   - $HOME 在 nu 字符串里不会自动展开,替换为绝对路径;
  #   - 值是字符串(环境变量无 list),逐项生成 $env.NAME = "…";
  #   - PATH 不含在此(zsh 走 pathInit),单独用 pathInitNu 设置。
  envAssignments = lib.mapAttrsToList (
    name: value:
    let
      v = lib.replaceStrings [ "$HOME" ] [ shared.home ] (toString value);
      v' = lib.escape [ "\\" "\"" ] v;
    in
    ''$env.${name} = "${v'}"''
  ) config.environment.variables;

  # set-environment 的 Extra initialisation 部分(不在 environment.variables)
  extraAssignments = [
    ''$env.NIX_PROFILES = "/nix/var/nix/profiles/default /run/current-system/sw ${shared.home}/.nix-profile"''
    ''$env.NIX_USER_PROFILE_DIR = "/nix/var/nix/profiles/per-user/${shared.username}"''
  ];

  # ── 生成的 env.nu ───────────────────────────────────────────────────
  # nushell 作为登录 shell 时不读 /etc/zshenv、不执行 path_helper,
  # 启动时 $env.PATH 为 nothing → 所有 nix/brew 工具(fastfetch、herdr…)
  # 都找不到。此文件在每次 nushell 启动时自动加载,重建 PATH 与全部
  # 环境变量(与 zsh 一致; GUI app 走 launchd agent, 见 shell/env.nix)。
  #
  # 注意 macOS 上 nushell 的默认配置目录是 ~/Library/Application Support/
  # nushell(而非 ~/.config/nushell)。
  envNu = pkgs.writeText "env.nu" ''
    # GENERATED by nix-darwin (modules/shell/nushell.nix) — DO NOT EDIT.
    # 与 environment.variables / zsh set-environment 同源,rebuild 自动同步。

    # ── PATH(顺序与 zsh lib.pathInit 严格一致)────────────────────────
    ${shared.pathInitNu}

    # ── 环境变量(来源: config.environment.variables)──────────────────
    ${lib.concatLines envAssignments}

    # ── Nix profile 元变量(set-environment Extra initialisation)───────
    ${lib.concatLines extraAssignments}
  '';

  # ── atuin 集成脚本 ──────────────────────────────────────────────────
  # 构建时运行 `atuin init nu`,把输出的 hooks/keybinding/搜索逻辑固化成
  # 静态 .nu 文件;运行时由 config.nu source。atuin 二进制必须已在 PATH
  # (env.nu 已保证)。
  #
  # 注意:atuin 18+ 的 `init` 需要写 ~/.config/atuin 加载设置,而 nix 沙箱
  # 的 HOME(/homeless-shelter)与 /tmp 均只读 → init 静默失败输出为空。
  # 解决:把 HOME 指到沙箱内唯一可写的 $TMPDIR(/nix/var/nix/builds/…),
  # 并预建配置目录。
  atuinNu = pkgs.runCommand "atuin.nu" { } ''
    export HOME="$TMPDIR"
    mkdir -p "$HOME/.config/atuin"
    ${lib.getExe pkgs.atuin} init nu > $out
  '';

  # ── zoxide 集成脚本 ─────────────────────────────────────────────────
  # zoxide 的官方做法是把 init 输出存成 ~/.zoxide.nu 再 source;这里在
  # 构建时固化,运行时 source 即可(提供 z / zi / __zoxide_* 等命令)。
  zoxideNu = pkgs.runCommand "zoxide.nu" { } ''
    ${lib.getExe pkgs.zoxide} init nushell > $out
  '';

  # ── 生成的 config.nu ────────────────────────────────────────────────
  # 加载 atuin/zoxide 集成 + zsh 习惯别名 + fzf 辅助命令。nushell 未覆盖
  # 的设置走内置 sensible defaults,故无需复制 500 行样板。
  # 注意:source 的路径含空格,必须加引号。
  configNu = pkgs.writeText "config.nu" ''
    # GENERATED by nix-darwin (modules/shell/nushell.nix) — DO NOT EDIT.
    # 集成 atuin / zoxide / fzf + 常用别名(与 zsh aliases.nix 对齐)。
    # 修改请改 nix 配置后 rebuild。

    # ── 基础 UI ───────────────────────────────────────────────────────
    $env.config.show_banner = false
    $env.config.history.max_size = 100000
    $env.config.history.sync_on_enter = true
    # 输入时灰色历史建议(类似 zsh-autosuggestions, nushell 0.112 内置):
    # 输命令时会提示下一条匹配历史,按 → / End 接受。
    # show_hints = true 启用;hinter.closure = null 用内置历史建议;
    # 建议颜色调亮一档(dark_gray → gray),更易察觉。
    $env.config.show_hints = true
    $env.config.hinter.closure = null
    $env.config.color_config.hints = "gray"

    # ── 目录导航(对应 zsh 的 .. 系列)────────────────────────────────
    alias .. = cd ..
    alias ... = cd ../..
    alias .... = cd ../../..
    alias ..... = cd ../../../..
    alias ..2 = cd ../..
    alias ..3 = cd ../../..

    # ── 编辑器 / 常用命令(对应 zsh aliases)──────────────────────────
    alias c = clear
    alias v = nvim
    alias vi = nvim
    alias vim = nvim
    alias g = git
    alias gc = git commit -v
    alias gst = git status -sb
    alias gl = git log --oneline --graph --decorate
    alias gp = git pull --rebase
    alias gd = git diff
    alias ga = git add -A

    # ── ls / cat 增强(zsh 用 eza/bat;nu 保留原生 ls 便于表格)───────
    alias ll = ^eza -lah --classify --sort=type
    alias la = ^eza -la
    alias tree = ^eza --tree --classify
    alias cat = ^bat --number

    # ── 模糊搜索(fzf 辅助命令,非交互式 keybinding)───────────────────
    # fcd:   交互式选择子目录并进入(替代 zsh ctrl-t + cd)
    # ff:    交互式选择文件,回显完整路径
    # fhist: atuin 交互式历史搜索(备用,ctrl-r 由 atuin 接管)
    def fcd [] {
        let dir = (^fd --type d --hidden --exclude .git --exclude node_modules --exclude .venv | ^fzf --preview '^eza --tree --classify -L 1 {}' --preview-window=right:60%)
        if ($dir | is-empty) { return }
        cd ($dir | str trim)
    }
    def ff [] {
        let file = (^fd --type f --hidden --exclude .git --exclude node_modules | ^fzf --preview '^bat --number --color=always {}' --preview-window=right:60%)
        if ($file | is-empty) { return }
        $file | str trim
    }
    def fhist [] {
        atuin search --interactive
    }

    # ── yazi(终端文件管理器):退出后 cd 到 yazi 最后所在目录 ─────────
    def --env y [...args] {
        let tmp = (mktemp -t "yazi-cwd.XXXXXX")
        ^yazi ...$args --cwd-file $tmp
        let cwd = (open $tmp)
        if $cwd != $env.PWD and ($cwd | path exists) {
            cd $cwd
        }
        rm -fp $tmp
    }

    # ── 集成:atuin(历史 hooks + ctrl-r)──────────────────────────────
    source "${shared.home}/Library/Application Support/nushell/atuin.nu"

    # ── 集成:zoxide(目录跳转 z / zi)─────────────────────────────────
    source "${shared.home}/Library/Application Support/nushell/zoxide.nu"
  '';

  # 目标目录:macOS 上 nushell 实际读取的配置路径
  nuConfigDir = "${shared.home}/Library/Application Support/nushell";
in
{
  # ── 安装 env.nu / atuin.nu / zoxide.nu / config.nu ─────────────────
  # 自定义 `system.activationScripts.<name>` 不会被执行(nix-darwin 只运行
  # 预定义脚本 + extraActivation),必须挂到 extraActivation.text 上。
  # activation 以 root 运行,故用绝对路径写文件并 chown 给用户。
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    # [nushell.nix] 写入 ~/Library/Application Support/nushell/
    install -d -m 0755 -o ${shared.username} -g staff "${nuConfigDir}"
    for f in env.nu atuin.nu zoxide.nu config.nu; do
      rm -f "${nuConfigDir}/$f"
    done
    install -m 0644 -o ${shared.username} -g staff ${envNu} "${nuConfigDir}/env.nu"
    install -m 0644 -o ${shared.username} -g staff ${atuinNu} "${nuConfigDir}/atuin.nu"
    install -m 0644 -o ${shared.username} -g staff ${zoxideNu} "${nuConfigDir}/zoxide.nu"
    install -m 0644 -o ${shared.username} -g staff ${configNu} "${nuConfigDir}/config.nu"
  '';
}
