{
  config,
  lib,
  pkgs,
  ...
}:
let
  shared = import ../lib.nix { };

  # ── 从单一来源生成环境变量赋值 ──────────────────────────────────────
  # environment.variables 是 nix-darwin 写入 launchd / zsh(set-environment)
  # 的同一来源。此处复用它生成 nu 语法,保证 zsh 与 nushell 永不漂移:
  # 任何变量改动(代理、LANG、PAGER…)rebuild 后两边自动同步。
  #
  # 处理:
  #   - $HOME 在 nu 字符串里不会自动展开,替换为绝对路径;
  #   - 值是字符串(环境变量无 list),逐项生成 $env.NAME = "…";
  #   - PATH 不含在此(zsh 走 pathInit),单独用 pathInitNu 设置。
  envAssignments = lib.mapAttrsToList (
    name: value:
    let
      v = lib.replaceStrings [ "$HOME" ] [ shared.home ] (toString value);
      v' = lib.escape [ "\\" "\"" ] v;
    in
    ''$env.${name} = "${v'}"''
  ) config.environment.variables;

  # set-environment 的 Extra initialisation 部分(不在 environment.variables)
  extraAssignments = [
    ''$env.NIX_PROFILES = "/nix/var/nix/profiles/default /run/current-system/sw ${shared.home}/.nix-profile"''
    ''$env.NIX_USER_PROFILE_DIR = "/nix/var/nix/profiles/per-user/${shared.username}"''
  ];

  # ── 生成的 env.nu ───────────────────────────────────────────────────
  # nushell 作为登录 shell 时不读 /etc/zshenv、不执行 path_helper,
  # 启动时 $env.PATH 为 nothing → 所有 nix/brew 工具(fastfetch、herdr…)
  # 都找不到。此文件在每次 nushell 启动时自动加载,重建 PATH 与全部
  # 环境变量(与 zsh / GUI 应用一致)。
  #
  # 注意 macOS 上 nushell 的默认配置目录是 ~/Library/Application Support/
  # nushell(而非 ~/.config/nushell)。
  #
  # 只管理 env.nu;config.nu(prompt/alias/插件)留给用户自行维护。
  envNu = pkgs.writeText "env.nu" ''
    # GENERATED by nix-darwin (modules/shell/nushell.nix) — DO NOT EDIT.
    # 与 environment.variables / zsh set-environment 同源,rebuild 自动同步。

    # ── PATH(顺序与 zsh lib.pathInit 严格一致)────────────────────────
    ${shared.pathInitNu}

    # ── 环境变量(来源: config.environment.variables)──────────────────
    ${lib.concatLines envAssignments}

    # ── Nix profile 元变量(set-environment Extra initialisation)───────
    ${lib.concatLines extraAssignments}
  '';

  # 目标目录:macOS 上 nushell 实际读取的配置路径
  nuConfigDir = "${shared.home}/Library/Application Support/nushell";
in
{
  # ── 安装 env.nu ─────────────────────────────────────────────────────
  # 自定义 `system.activationScripts.<name>` 不会被执行(nix-darwin 只运行
  # 预定义脚本 + extraActivation),必须挂到 extraActivation.text 上。
  # activation 以 root 运行,故用绝对路径写文件并 chown 给用户。
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    # [nushell.nix] 写入 ~/Library/Application Support/nushell/env.nu
    install -d -m 0755 -o ${shared.username} -g staff "${nuConfigDir}"
    rm -f "${nuConfigDir}/env.nu"
    install -m 0644 -o ${shared.username} -g staff ${envNu} "${nuConfigDir}/env.nu"
  '';
}
